# Generated by Django 5.2.8 on 2025-11-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Salesperson', 'Salesperson'), ('Manager', 'Manager'), ('Inventory', 'Inventory Manager'), ('Admin', 'Administrator'), ('Support', 'Support Staff'), ('Accountant', 'Accountant'), ('HR', 'Human Resources')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='company.company')),
                ('groups', models.ManyToManyField(blank=True, related_name='company_set', related_query_name='company', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='company_permissions_set', related_query_name='company_permission', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
