# Generated by Django 6.0.2 on 2026-02-18 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branch', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Development', 'Development'), ('Manager', 'Manager'), ('Inventory_Manager', 'Inventory Manager'), ('Admin', 'Administrator'), ('Support', 'Support Staff'), ('Accountant', 'Accountant'), ('HR_Manager', 'Human Resources'), ('Cashier', 'Cashier'), ('Staff', 'Staff')], max_length=50)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern'), ('freelancer', 'Freelancer'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('whatsapp_opt_in_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='branch.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='company_set', related_query_name='company', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='company_permissions_set', related_query_name='company_permission', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
