from accounts.admin.account_register import *
from accounts.admin.bank_account_register import *
from accounts.admin.branch_account_register import *
from accounts.admin.cash_account_register import *
from accounts.admin.customer_account_register import *
from accounts.admin.employee_account_register import *
from accounts.admin.expense_account_register import *
from accounts.admin.loan_account_register import *
from accounts.admin.purchases_account_register import *
from accounts.admin.purchases_returns_register import *
from accounts.admin.sales_account_register import *
from accounts.admin.sales_returns_account_register import *
from accounts.admin.supplier_account_register import *
from accounts.admin.writeoff_account_register import *