# Generated by Django 5.2.8 on 2025-11-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branch', '0001_initial'),
        ('company', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='company.company'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accounts', to='accounts.account'),
        ),
    ]
