# Generated by Django 5.2.8 on 2025-11-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='loans.loan'),
        ),
        migrations.AlterUniqueTogether(
            name='branchaccount',
            unique_together={('branch', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='customeraccount',
            unique_together={('customer', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeaccount',
            unique_together={('employee', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='loanaccount',
            unique_together={('loan', 'account')},
        ),
    ]
