# Generated by Django 5.2.8 on 2026-02-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('branch', '0001_initial'),
        ('company', '0001_initial'),
        ('currency', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='company.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='company.company'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_account', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accounts', to='branch.branch'),
        ),
    ]
