# Generated by Django 6.0.2 on 2026-02-18 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0003_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='suppliers.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='suppliers.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='suppliers.purchasereturn'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales.salesreturn'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_takes', to='users.user'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to='users.user'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_stock_takes', to='users.user'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='stocktakeapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_approvals', to='users.user'),
        ),
        migrations.AddField(
            model_name='stocktakeapproval',
            name='stock_take',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='stockwriteoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='stockwriteoffitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockwriteoffitem',
            name='write_off',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockwriteoff'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['company', 'branch', 'name'], name='inventory_p_company_b24beb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('company', 'branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'branch', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'branch')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='inventory_s_product_cbdc37_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeapproval',
            unique_together={('stock_take', 'approved_by')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockwriteoffitem',
            index=models.Index(fields=['write_off', 'product'], name='inventory_s_write_o_d14cfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockwriteoffitem',
            unique_together={('write_off', 'product')},
        ),
    ]
