# Generated by Django 5.2.8 on 2025-11-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='perfomed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take', 'product')},
        ),
    ]
