from django.contrib import admin
from suppliers.models import *

admin.site.register(PurchaseItem)
admin.site.register(PurchaseInvoiceItem)
admin.site.register(PurchaseInvoice)
admin.site.register(Purchase)
admin.site.register(PurchaseOrderItem)
admin.site.register(PurchaseOrder)
admin.site.register(PurchasePaymentAllocation)
admin.site.register(PurchasePayment)
admin.site.register(PurchaseReturnItem)
admin.site.register(PurchaseReturn)
admin.site.register(SupplierCreditNoteItem)
admin.site.register(SupplierCreditNote)
admin.site.register(SupplierDebitNoteItem)
admin.site.register(SupplierDebitNote)
admin.site.register(Supplier)
admin.site.register(SupplierReceiptItem)
admin.site.register(SupplierReceipt)