# Generated by Django 6.0.2 on 2026-02-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.user'),
        ),
        migrations.AddField(
            model_name='loan',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower'], name='loans_loan_borrowe_4ce53f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['issued_by'], name='loans_loan_issued__e4d27f_idx'),
        ),
    ]
