from sales.admin import delivery_note_item_register
from sales.admin import delivery_note_register
from sales.admin import delivery_note_item_register
from sales.admin import sale_register
from sales.admin import sales_invoice_item_register
from sales.admin import sales_invoice_register
from sales.admin import sales_order_item_register
from sales.admin import sales_order_register
from sales.admin import sales_quotation_item_register
from sales.admin import sales_quotation_register
from sales.admin import sales_receipt_item_register
from sales.admin import sales_receipt_register
from sales.admin import sales_return_item_register
from sales.admin import sales_return_register